<template>
  <div class="tools-page-container">
    <div class="tools-container">
        <el-icon class="tools-icon" style="font-size: 36px;"><SetUp /></el-icon>
        <h1>Tools</h1>
    </div>

        <div style="display:flex;justify-content:space-between;flex-wrap: wrap;width: 100%;padding-top: 30px">
          <!-- 搜索 Novel Sequences-->
          <div class="card-grid">
            <div data-aos="fade-up" class="digit-card2">
              <div style="font-size:28px;font-weight:650;text-align:left;color:#44484d">
                <el-icon :size="28"><InfoFilled /></el-icon>
                DeepSeek-V3 Model
              </div>
              <div style="font-size:16px;font-weight:440;text-align:left ;color:#61718d;">
                We provide DeepSeek-V3 model from siliconflow's API, allowing users to query different types of questions limited in 40 words, or you can input a gene name to get an answer generated by a LLM.
              </div>
            </div>

          <!-- 搜索  Potential HAA Genes-->
            <div data-aos="fade-up" class="digit-card2">
              <div style="font-size:28px;font-weight:650;text-align:left;color:#44484d">
                <el-icon :size="28"><InfoFilled /></el-icon>
                Data Upload Searching
              </div>
              <div style="font-size:16px;font-weight:400;text-align:left ;color:#61718d;">
                We provide a large-scale population data foundation with continuous growth, you can upload a EXCEL file containing the chromosome and location information of SNPs to obtain batch genetic variation data in PGG.AF1M.
              </div>
            </div>

          <!-- 搜索  Plateau-specific SVs-->
            <div data-aos="fade-up" class="digit-card2">
              <div style="font-size:28px;font-weight:650;text-align:left;color:#44484d">
                <el-icon :size="28"><InfoFilled /></el-icon>
                Imputation Panel
              </div>
              <div style="font-size:16px;font-weight:400;text-align:left ;color:#61718d;">
                We provide an imputation panel by PGG.Han. It supports aggregate population queries as well as cross-group comparative analyses (e.g., by ethnicity or other cohorts).
              </div>
            </div>

            <div data-aos="fade-up" class="digit-card2">
              <div style="font-size:28px;font-weight:650;text-align:left;color:#44484d">
                <el-icon :size="28"><InfoFilled /></el-icon>
                IBD
              </div>
              <div style="font-size:16px;font-weight:400;text-align:left ;color:#61718d;">
                We provide diverse spectrum data, including ref/alt alleles, sample size, and genotype frequencies, with external links to cross-reference major databases (e.g., gnomAD).
              </div>
            </div>

        </div>
      </div>

    <!-- 包裹内容的框 -->
    <div class="tools-content-box">
      <div class="tools-photo-container">
            <!-- <img src="@/assets/images/AnalysisPipeline.png" alt="Centered Image"> -->
      </div>
      <p style="font-size: 20px;font-weight: bold;text-align: center;">Choose the tool section you would like to use.</p>
      <!-- 导航栏 -->
      <div class="tools-navigation-container">
        <router-link to="/tools/DeepSeek" class="tools-navigation-item">DeepSeek</router-link>
        <router-link to="/tools/DataUpload" class="tools-navigation-item">DataUpload</router-link>
        <router-link to="/tools/Imputation" class="tools-navigation-item">Imputation</router-link>
        <!-- <router-link to="/tools/GWAS" class="tools-navigation-item">GWAS</router-link> -->
        <router-link to="/tools/IBD" class="tools-navigation-item">IBD</router-link>
<!--         <router-link to="/tools/BLAST" class="tools-navigation-item">BLAST</router-link> -->
      </div>

      <!-- 其他内容 -->
      <div class="tools-content-container"> <!-- 二级路由的内容放在这里配置展示 -->
        <router-view/>
      </div>
    </div>
  </div>
</template>

<style>
.tools-page-container {
  display: flex;
  flex-direction: column;
  width: 90%;
  margin: 0 auto;
  background: linear-gradient(to bottom, #f5f7fa, #ffffff); /* 高级感背景 */
  border-radius: 15px;
  box-shadow: 0 8px 20px rgba(0, 0, 0, 0.1);
  padding: 20px;
}
.tools-container {
  display: flex;
  align-items: center;
  padding: 20px;
  background: linear-gradient(to right, #3a6073, #16222a); /* 深色背景 */
  color: white;
  border-radius: 15px;
  box-shadow: 0 6px 12px rgba(0, 0, 0, 0.15);
}

.tools-photo-container {
    text-align: center; /* 将图像居中 */
    margin-top: 20px; /* 添加上边距 */
    margin-bottom: 20px; /* 添加下边距 */
}

.tools-photo-container img {
    width: 70%; /* 设置图像宽度为900px */
    height: 70%; /* 设置图像高度为600px */
    display: block; /* 设置图像为块级元素，以便居中显示 */
    margin: 20px auto; /* 设置上下边距为20px，左右居中 */
}
.tools-content-box {
  background-color: white;
  padding: 20px;
  border-radius: 5px; /* 可以添加圆角效果 */
  margin-top: 20px; /* 可以调整框与导航栏之间的间距 */
}

.tools-container {
  display: flex;
  padding: 20px;
}
.tools-content-container{
  flex: 1;
  
}
.tools-navigation-container {
  display: flex;
  justify-content: space-around;
  margin-top: 20px;
  background: linear-gradient(to right, #3a6073, #16222a); /* 渐变背景色 */
  border-radius: 10px; /* 边框圆角 */
  padding: 10px;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); /* 阴影效果 */
}

.tools-navigation-item {
  font-size: 18px;
  font-weight: bold;
  color: #ecf0f1; /* 默认字体颜色 */
  flex: 1;
  text-align: center;
  padding: 15px;
  border-radius: 8px; /* 边框圆角 */
  cursor: pointer;
  margin: 0 20px; /* 间距 */
  background-color: transparent; /* 透明背景 */
  transition: all 0.3s ease; /* 添加过渡效果 */
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); /* 阴影效果 */
}

.tools-navigation-item:hover {
  background-color: rgba(255, 255, 255, 0.2); /* 悬浮透明白色背景 */
  transform: scale(1.05); /* 缩放效果 */
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); /* 放大阴影 */
}

.tools-navigation-item.router-link-active {
  background-color: #1abc9c; /* 激活状态的背景色 */
  color: #ffffff; /* 激活状态的字体颜色 */
  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3); /* 深色阴影 */
  transform: scale(1.1); /* 激活状态稍微放大 */
}

.card-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 30px;
  padding-top: 0px;
}

.digit-card2 {
  background-color: #fff;
  border-radius: 12px;
  padding: 20px;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.05);
  transition: transform 0.2s;
}

.digit-card2:hover {
  transform: translateY(-5px);
}

.digit-card2 i {
  color: #1a73e8;
  font-size: 35px;
  font-weight: 800;
  margin-bottom: 10px;
}

.digit-card2-title {
  font-size: 28px;
  font-weight: 650;
  color: #44484d;
  margin-bottom: 10px;
}

.digit-card2-desc {
  font-size: 16px;
  font-weight: 400;
  color: #61718d;
  line-height: 1.5;
}
</style>
